CREATE TABLE SCHEMA_VERSION(
    ID VARCHAR(255),
    VERSION VARCHAR(255),
    DETAIL_TYPE VARCHAR(255),
    SOURCE VARCHAR(255),
    ACCOUNT VARCHAR(255),
    CREATE_TIME VARCHAR(255),
    REGION VARCHAR(255),
    DETAIL VARCHAR(255)
);

INSERT INTO SCHEMA_VERSION(ID, VERSION, DETAIL_TYPE, SOURCE, ACCOUNT, CREATE_TIME, REGION, DETAIL) VALUES (?, ?, ?, ?, ?, ?, ?, ?);